"""Canonical list of genera to track across papers."""

CANONICAL_GENERA = [
    "Abies", "Acanthus", "Acer", "Achillea", "Achnatherum", "Adonis", "Aesculus",
    "Agrimonia", "Agropyron", "Agrostemma", "Alchemilla", "Allium", "Alnus", "Aloe",
    "Althaea", "Amanita", "Amaranthus", "Anacamptis", "Anchusa", "Anethum", "Apium",
    "Arbutus", "Arctium", "Arctostaphylos", "Aria", "Aronia", "Artemisia",
    "Asphodelus", "Asplenium", "Astragalus", "Athamanta", "Atriplex", "Atropa",
    "Avena", "Bellis", "Beta", "Betula", "Blitum", "Brassica", "Bryonia", "Bunium",
    "Buxus", "Calendula", "Calluna", "Caltha", "Campanula", "Cannabis", "Capsella",
    "Capsicum", "Carlina", "Carpinus", "Cassia", "Castanea", "Centaurea",
    "Centaurium", "Cetraria", "Chamomilla", "Chelidonium", "Chenopodium", "Cicer",
    "Cichorium", "Citrullus", "Citrus", "Clematis", "Clinopodium", "Colchicum",
    "Colutea", "Convolvulus", "Cormus", "Cornus", "Corylus", "Cotinus", "Crataegus",
    "Crocus", "Cucumis", "Cucurbita", "Cydonia", "Cynara", "Cynodon", "Dactylorhiza",
    "Datura", "Daucus", "Dryopteris", "Ecballium", "Equisetum", "Eruca", "Euonymus",
    "Euphorbia", "Fagus", "Faseolus", "Ficus", "Foeniculum", "Fragaria", "Fraxinus",
    "Fumaria", "Galium", "Gentiana", "Geranium", "Geum", "Glechoma", "Glycine",
    "Helianthus", "Helicrysum", "Helleborus", "Hordeum", "Humulus", "Hylotelephium",
    "Hypericum", "Hyoscyamus", "Ilex", "Inula", "Iris", "Juglans", "Juncus",
    "Juniperus", "Lactuca", "Lagenaria", "Lathyrus", "Laurus", "Lavandula",
    "Leonurus", "Lolium", "Lunaria", "Lycoperdon", "Lycopersicon", "Lycopodium",
    "Malus", "Malva", "Marrubium", "Matricaria", "Melissa", "Mentha", "Mespilus",
    "Momordica", "Morus", "Mutarda", "Narcissus", "Neotinea", "Nepeta", "Nicotiana",
    "Ocimum", "Olea", "Ophrys", "Orchis", "Origanum", "Oryza", "Ostrya", "Papaver",
    "Pelargonium", "Petroselinum", "Phaseolus", "Pimpinella", "Pinguicula", "Pinus",
    "Piper", "Plantago", "Platanus", "Polygonum", "Populus", "Portulaca", "Primula",
    "Prunus", "Pteridium", "Pulmonaria", "Punica", "Pyrus", "Quercus", "Raphanus",
    "Ribes", "Robinia", "Rosa", "Rubia", "Rubus", "Rumex", "Salix", "Salvia",
    "Sambucus", "Satureja", "Scrophularia", "Secale", "Sedum", "Sempervivum",
    "Sideritis", "Silene", "Silybum", "Solanum", "Sonchus", "Spartium", "Spinacia",
    "Staehelina", "Stipa", "Symphytum", "Syringa", "Syzygium", "Tanacetum",
    "Taraxacum", "Teucrium", "Thymus", "Tilia", "Tragopogon", "Trifolium",
    "Trigonella", "Triticum", "Tussilago", "Typha", "Ulmus", "Urtica", "Vaccinium",
    "Valeriana", "Veratrum", "Verbascum", "Veronica", "Vicia", "Vinca", "Viola",
    "Viscum", "Vitis", "Zea",
]

CANONICAL_SET = set(CANONICAL_GENERA)
